drop table TB_POST IF exists;

create table TB_POST (
    POST_ID bigint generated by default as identity,
    TITLE varchar(255) not null,
    SUBTITLE varchar(255),
    LINK varchar(255),
    WRITTER varchar(255) not null,
    UPDATED timestamp,
    CONTENT varchar(255),
    BG_IMAGE varchar(255),
    primary key (POST_ID)
) 